[project]
name = "my-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "adafruit-blinka>=9.2.0",
    "adafruit-circuitpython-vl53l0x>=3.6.19",
    "gpiozero>=2.0.1.post3",
    "numpy>=2.5.1",
    "opencv-python>=5.0.0.93",
    "torch>=2.13.0",
    "torchvision>=0.28.0",
]

[project.scripts]
project = "project:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
